### ISSUE TITLE
ids.dbs not pre-generated by Management Console

### ISSUE THREAD

**Issue by shakna-israel** [shakna-israel/doccu#32]
``` python
λ doccu-manage
Enter 1 to ADD a user
2 to REMOVE a User
3 to START the server
4 to updated browser-based dependencies
5 to updateserver-based dependencies:1
Enter a users UNIQUE name, e.g. Trevor Clough: James Milne
Enter a users UNIQUE code, e.g. 00226677 002255
Traceback (most recent call last):
  File "C:\Users\s4b3r_000\doccu\doccu-manage.py", line 170, in <module>
    main()
  File "C:\Users\s4b3r_000\doccu\doccu-manage.py", line 130, in main
    generate_id(unique_name,unique_code)
  File "C:\Users\s4b3r_000\doccu\doccu-manage.py", line 15, in generate_id
    db = pickle.load(open(doccu_home + "/ids.dbs", "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\s4b3r_000/.doccu/ids.dbs'
```

**Comment by shakna-israel** [comment]
Fixed in 893e672cacf04212482af6684d15cb3b2b976cc2
